style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/LightForm-group/damask-parse
options:
  commits:
    filters:
      Type:
        - feat
        - update
        - perf
        - fix
        - refactor
        - build
        - chore
  commit_groups:
    title_maps:
      feat: âœ¨ Features
      fix: ğŸ› Bug Fixes
      perf: âš¡ Performance Improvements
      refactor: â™» Code Refactoring
      update: ğŸ”„ Updates
      build: ğŸ‘· Build changes
      chore: Other changes
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
